import type { Contact } from "@/types/index";

/**
 * Generated by scripts/import-account-contacts.mjs — do not edit by hand.
 * Re-run: npm run import:contacts
 */
export const ACCOUNT_CONTACTS_SEED: Contact[] = [
  {
    "id": "seed-acct-03-2",
    "account_id": "acct-03",
    "full_name": "Larry Simmons",
    "title": "",
    "email": "",
    "phone": "",
    "address": "",
    "notes": ""
  },
  {
    "id": "seed-acct-04-3",
    "account_id": "acct-04",
    "full_name": "Sven Stricker",
    "title": "",
    "email": "",
    "phone": "",
    "address": "",
    "notes": ""
  },
  {
    "id": "seed-acct-04-4",
    "account_id": "acct-04",
    "full_name": "R. Heath Cheek",
    "title": "",
    "email": "",
    "phone": "",
    "address": "",
    "notes": ""
  },
  {
    "id": "seed-acct-05-5",
    "account_id": "acct-05",
    "full_name": "Andrew Bynum",
    "title": "",
    "email": "abynum@burnscharest.com",
    "phone": "14699404549",
    "address": "",
    "notes": "Main 14699044550 · Mobile 12149836358"
  },
  {
    "id": "seed-acct-05-6",
    "account_id": "acct-05",
    "full_name": "Daniel Charest",
    "title": "",
    "email": "dcharest@burnscharest.com",
    "phone": "14699044555",
    "address": "",
    "notes": "Main 14699044550 · Mobile 12146818444"
  },
  {
    "id": "seed-acct-05-7",
    "account_id": "acct-05",
    "full_name": "Larry Vincent",
    "title": "",
    "email": "lvincent@burnscharest.com",
    "phone": "14699044557",
    "address": "",
    "notes": "Main 14699044550 · Mobile 12146801668"
  },
  {
    "id": "seed-acct-06-8",
    "account_id": "acct-06",
    "full_name": "Frank Piccolo",
    "title": "",
    "email": "frank.piccolo@chaffe.com",
    "phone": "17133432950",
    "address": "801 Travis Street, Suite 1910, Houston, TX, 77002, USA",
    "notes": "Main 17133432949"
  },
  {
    "id": "seed-acct-06-9",
    "account_id": "acct-06",
    "full_name": "Kenneth Tribuch",
    "title": "",
    "email": "kenneth.tribuch@chaffe.com",
    "phone": "17133132953",
    "address": "",
    "notes": "Main 17133432949"
  },
  {
    "id": "seed-acct-06-10",
    "account_id": "acct-06",
    "full_name": "Caroline Webb",
    "title": "Associate",
    "email": "caroline.webb@chaffe.com",
    "phone": "713-343-2949",
    "address": "801 Travis Street, Suite 1910, Houston, TX, 77002, USA",
    "notes": ""
  },
  {
    "id": "seed-acct-07-11",
    "account_id": "acct-07",
    "full_name": "Barrie Beer",
    "title": "",
    "email": "bbeer@chartwelllaw.com",
    "phone": "17137034935",
    "address": "",
    "notes": "Main 15128566352"
  },
  {
    "id": "seed-acct-41-12",
    "account_id": "acct-41",
    "full_name": "Tamir Robinson",
    "title": "",
    "email": "Tamir_Robinson@cinfin.com",
    "phone": "15125686014",
    "address": "",
    "notes": ""
  },
  {
    "id": "seed-acct-09-13",
    "account_id": "acct-09",
    "full_name": "Karl Schulz",
    "title": "Partner",
    "email": "kschulz@cozen.com",
    "phone": "18325634176",
    "address": "",
    "notes": "Main 18322143933 · Mobile 17132969336"
  },
  {
    "id": "seed-acct-09-14",
    "account_id": "acct-09",
    "full_name": "Stephan Pate",
    "title": "",
    "email": "",
    "phone": "18322143933",
    "address": "",
    "notes": ""
  },
  {
    "id": "seed-acct-11-15",
    "account_id": "acct-11",
    "full_name": "Bart Scott",
    "title": "",
    "email": "bscott@eberls.com",
    "phone": "303-986-2771",
    "address": "3900 S Wadsworth Blvd, #800, Lakewood, CO, 80235, USA",
    "notes": ""
  },
  {
    "id": "seed-acct-12-16",
    "account_id": "acct-12",
    "full_name": "Steven Phillips",
    "title": "Executive General Adjuster",
    "email": "sphillips@englemartin.com",
    "phone": "214-239-0928",
    "address": "17304 Preston Road, Suite 975, Dallas, TX, 75252",
    "notes": ""
  },
  {
    "id": "seed-acct-12-17",
    "account_id": "acct-12",
    "full_name": "Ruben Gaztambide",
    "title": "",
    "email": "Ruben.Gaztambide@EngleMartin.com",
    "phone": "18608103436",
    "address": "",
    "notes": "Main 15122765356"
  },
  {
    "id": "seed-acct-12-18",
    "account_id": "acct-12",
    "full_name": "Paul Cawood",
    "title": "",
    "email": "pcawood@englemartin.com",
    "phone": "15122765654",
    "address": "",
    "notes": "Main 12142390928 · Mobile 15124231406"
  },
  {
    "id": "seed-acct-12-19",
    "account_id": "acct-12",
    "full_name": "Chris Van Rees",
    "title": "National General Adjuster",
    "email": "chris.vanrees@okstatealumni.org",
    "phone": "469-400-8668",
    "address": "17304 Preston Road, Suite 975, Dallas, TX, 75252",
    "notes": ""
  },
  {
    "id": "seed-acct-13-20",
    "account_id": "acct-13",
    "full_name": "Christiaan Visser",
    "title": "",
    "email": "cvisser@fedins.com",
    "phone": "817-358-7299",
    "address": "PO Box 486, Owatonna, MN, 55060, USA",
    "notes": ""
  },
  {
    "id": "seed-acct-13-21",
    "account_id": "acct-13",
    "full_name": "Tony Mosty",
    "title": "",
    "email": "tmosty@fedins.com",
    "phone": "817-705-6111",
    "address": "PO Box 486, Owatonna, MN, 55060, USA",
    "notes": ""
  },
  {
    "id": "seed-acct-13-22",
    "account_id": "acct-13",
    "full_name": "Dawn Willeford",
    "title": "",
    "email": "dwilleford@fedins.com",
    "phone": "806-786-0884",
    "address": "PO Box 486, Owatonna, MN, 55060, USA",
    "notes": ""
  },
  {
    "id": "seed-acct-13-23",
    "account_id": "acct-13",
    "full_name": "Carolyn Jensen",
    "title": "",
    "email": "cjensen@fedins.com",
    "phone": "210-410-5542",
    "address": "PO Box 486, Owatonna, MN, 55060, USA",
    "notes": ""
  },
  {
    "id": "seed-acct-15-24",
    "account_id": "acct-15",
    "full_name": "Mike Shipman",
    "title": "",
    "email": "mike.shipman@fletcherfarley.com",
    "phone": "12149879600",
    "address": "",
    "notes": ""
  },
  {
    "id": "seed-acct-18-25",
    "account_id": "acct-18",
    "full_name": "Alexander Whitlock",
    "title": "",
    "email": "alex@guildaylaw.com",
    "phone": "18507014354",
    "address": "",
    "notes": "Main 18502247091"
  },
  {
    "id": "seed-acct-18-26",
    "account_id": "acct-18",
    "full_name": "George Hatch",
    "title": "",
    "email": "george@guildaylaw.com",
    "phone": "18502247091",
    "address": "",
    "notes": ""
  },
  {
    "id": "seed-acct-20-27",
    "account_id": "acct-20",
    "full_name": "Brandon Wilson",
    "title": "",
    "email": "brandonw@hermes-law.com",
    "phone": "12147496800 ext 214-749-6582",
    "address": "",
    "notes": ""
  },
  {
    "id": "seed-acct-20-28",
    "account_id": "acct-20",
    "full_name": "Max Bayman",
    "title": "",
    "email": "max@hermes-law.com",
    "phone": "12147496800 ext 214-749-6511",
    "address": "",
    "notes": ""
  },
  {
    "id": "seed-acct-20-29",
    "account_id": "acct-20",
    "full_name": "Austin Williams",
    "title": "",
    "email": "austin@hermes-law.com",
    "phone": "12147496800 ext 214-749-6823",
    "address": "",
    "notes": ""
  },
  {
    "id": "seed-acct-21-30",
    "account_id": "acct-21",
    "full_name": "Steve Johanson",
    "title": "",
    "email": "sjohanson@k2insclaims.com",
    "phone": "17602800182",
    "address": "",
    "notes": "Main 18588668966"
  },
  {
    "id": "seed-acct-21-31",
    "account_id": "acct-21",
    "full_name": "Jeff Marsh",
    "title": "Sr. Claims Examiner",
    "email": "jmarsh@k2insclaims.com",
    "phone": "18152197619",
    "address": "",
    "notes": "Main 18002332160 · Ext 3105"
  },
  {
    "id": "seed-acct-28-32",
    "account_id": "acct-28",
    "full_name": "Amber Dunton",
    "title": "",
    "email": "dunton@mdjwlaw.com",
    "phone": "713-632-1790",
    "address": "808 Travis, 20th Floor, Houston, TX, 77002",
    "notes": ""
  },
  {
    "id": "seed-acct-28-33",
    "account_id": "acct-28",
    "full_name": "Jamie Cooper",
    "title": "",
    "email": "cooper@mdjwlaw.com",
    "phone": "17136321700",
    "address": "",
    "notes": ""
  },
  {
    "id": "seed-acct-28-34",
    "account_id": "acct-28",
    "full_name": "Barrie Beer",
    "title": "",
    "email": "beer@mdjwlaw.com",
    "phone": "713-632-1713",
    "address": "808 Travis, 20th Floor, Houston, TX, 77002",
    "notes": ""
  },
  {
    "id": "seed-acct-30-35",
    "account_id": "acct-30",
    "full_name": "Jacquelyn Williams",
    "title": "",
    "email": "williaj3@nationwide.com",
    "phone": "18444017997 ext 13176",
    "address": "",
    "notes": ""
  },
  {
    "id": "seed-acct-31-36",
    "account_id": "acct-31",
    "full_name": "Gregory Donoian",
    "title": "",
    "email": "GDonoian@narisk.com",
    "phone": "13212078090",
    "address": "",
    "notes": "Main 18003156090"
  },
  {
    "id": "seed-acct-31-37",
    "account_id": "acct-31",
    "full_name": "Peter Adami",
    "title": "",
    "email": "padami@narisk.com",
    "phone": "13214411495",
    "address": "",
    "notes": "Main 18003156090"
  },
  {
    "id": "seed-acct-31-38",
    "account_id": "acct-31",
    "full_name": "Andrew Hollick",
    "title": "",
    "email": "ahollick@narisk.com",
    "phone": "13212823447",
    "address": "",
    "notes": "Main 18003156090"
  },
  {
    "id": "seed-acct-31-39",
    "account_id": "acct-31",
    "full_name": "Mark Pierce",
    "title": "",
    "email": "MPierce@narisk.com",
    "phone": "13214411203",
    "address": "",
    "notes": "Main 13124411203"
  },
  {
    "id": "seed-acct-32-40",
    "account_id": "acct-32",
    "full_name": "Stephaine Erhart",
    "title": "",
    "email": "",
    "phone": "",
    "address": "",
    "notes": ""
  },
  {
    "id": "seed-acct-35-41",
    "account_id": "acct-35",
    "full_name": "Bill Barfield",
    "title": "",
    "email": "bill@porterfirm.com",
    "phone": "17136210700",
    "address": "",
    "notes": ""
  },
  {
    "id": "seed-acct-35-42",
    "account_id": "acct-35",
    "full_name": "David Augustus",
    "title": "",
    "email": "daugustus@porterfirm.com",
    "phone": "17136240700",
    "address": "",
    "notes": ""
  },
  {
    "id": "seed-acct-38-43",
    "account_id": "acct-38",
    "full_name": "Kenneth Williams",
    "title": "Shareholder",
    "email": "kwilliams@smsm.com",
    "phone": "15124767834",
    "address": "",
    "notes": ""
  },
  {
    "id": "seed-acct-38-44",
    "account_id": "acct-38",
    "full_name": "Patrick Kemp",
    "title": "",
    "email": "pkemp@smsm.com",
    "phone": "15124767834",
    "address": "",
    "notes": ""
  },
  {
    "id": "seed-acct-39-45",
    "account_id": "acct-39",
    "full_name": "Brannon Dillard",
    "title": "",
    "email": "",
    "phone": "18324151801",
    "address": "",
    "notes": ""
  },
  {
    "id": "seed-acct-39-46",
    "account_id": "acct-39",
    "full_name": "Jay W. Brown",
    "title": "",
    "email": "jbrown@shackelford.law",
    "phone": "832-415-1775",
    "address": "717 Texas Ave., 27th Floor, Houston, TX, 77002, USA",
    "notes": ""
  },
  {
    "id": "seed-acct-39-47",
    "account_id": "acct-39",
    "full_name": "Kail Hidalgo",
    "title": "",
    "email": "khidalgo@shackelford.law",
    "phone": "18324151791",
    "address": "",
    "notes": "Main 18324151801"
  },
  {
    "id": "seed-acct-39-48",
    "account_id": "acct-39",
    "full_name": "Bruce Wilkin",
    "title": "Partner",
    "email": "bwilkin@shackelford.law",
    "phone": "832-415-1773",
    "address": "717 Texas Ave., 27th Floor, Houston, TX, 77002",
    "notes": ""
  },
  {
    "id": "seed-acct-42-49",
    "account_id": "acct-42",
    "full_name": "Jennifer Kearns",
    "title": "",
    "email": "",
    "phone": "",
    "address": "701 Brazos, Suite 1500, Austin, TX, 78701",
    "notes": ""
  },
  {
    "id": "seed-acct-42-50",
    "account_id": "acct-42",
    "full_name": "Jay Thompson",
    "title": "",
    "email": "",
    "phone": "",
    "address": "701 Brazos, Suite 1500, Austin, TX, 78701",
    "notes": ""
  },
  {
    "id": "seed-acct-43-51",
    "account_id": "acct-43",
    "full_name": "Kolby Keller",
    "title": "",
    "email": "KKeller@thompsoncoe.com",
    "phone": "12148718200",
    "address": "",
    "notes": ""
  },
  {
    "id": "seed-acct-43-52",
    "account_id": "acct-43",
    "full_name": "Trey Wilson",
    "title": "",
    "email": "",
    "phone": "",
    "address": "700 North Pearl Street, 25th floor - Plaza of the Americas, Dallas, TX, 75201, USA",
    "notes": ""
  },
  {
    "id": "seed-acct-43-53",
    "account_id": "acct-43",
    "full_name": "J.Richard Thompson",
    "title": "",
    "email": "",
    "phone": "",
    "address": "700 North Pearl Street, 25th floor - Plaza of the Americas, Dallas, TX, 75201, USA",
    "notes": ""
  },
  {
    "id": "seed-acct-43-54",
    "account_id": "acct-43",
    "full_name": "Rhonda Thompson",
    "title": "",
    "email": "rthompson@thompsoncoe.com",
    "phone": "214-871-8273",
    "address": "700 North Pearl Street, 25th floor - Plaza of the Americas, Dallas, TX, 75201, USA",
    "notes": ""
  },
  {
    "id": "seed-acct-44-55",
    "account_id": "acct-44",
    "full_name": "Mark Kressenberg",
    "title": "",
    "email": "",
    "phone": "17134038210",
    "address": "",
    "notes": ""
  },
  {
    "id": "seed-acct-44-56",
    "account_id": "acct-44",
    "full_name": "Jay Simon",
    "title": "",
    "email": "jsimon@thompsoncoe.com",
    "phone": "713-403-8216",
    "address": "One Riverway, Suite 1400, Houston, TX, 77056, United States",
    "notes": ""
  },
  {
    "id": "seed-acct-44-57",
    "account_id": "acct-44",
    "full_name": "Bob Lamb",
    "title": "",
    "email": "",
    "phone": "17134038210",
    "address": "",
    "notes": ""
  },
  {
    "id": "seed-acct-44-58",
    "account_id": "acct-44",
    "full_name": "Jason Yacuk",
    "title": "",
    "email": "jyacuk@thompsoncoe.com",
    "phone": "713-403-8385",
    "address": "One Riverway, Suite 1400, Houston, TX, 77056, United States",
    "notes": ""
  },
  {
    "id": "seed-acct-44-59",
    "account_id": "acct-44",
    "full_name": "George Arnold",
    "title": "",
    "email": "garnold@thompsoncoe.com",
    "phone": "713-403-8388",
    "address": "One Riverway, Suite 1400, Houston, TX, 77056, United States",
    "notes": "Mobile 281-403-8388"
  },
  {
    "id": "seed-acct-44-60",
    "account_id": "acct-44",
    "full_name": "Susan Usery",
    "title": "Senior Attorney",
    "email": "susery@thompsoncoe.com",
    "phone": "17134038244",
    "address": "",
    "notes": "Main 17134038210"
  },
  {
    "id": "seed-acct-45-61",
    "account_id": "acct-45",
    "full_name": "Lisa Songy",
    "title": "",
    "email": "lisas@tbmmlaw.com",
    "phone": "12146650107",
    "address": "",
    "notes": ""
  },
  {
    "id": "seed-acct-51-62",
    "account_id": "acct-51",
    "full_name": "Accounts Payable",
    "title": "",
    "email": "AccountsPayable@Zelle.com",
    "phone": "12147423000",
    "address": "",
    "notes": ""
  },
  {
    "id": "seed-acct-51-63",
    "account_id": "acct-51",
    "full_name": "Steven J. Badger",
    "title": "Partner",
    "email": "sbadger@zelle.com",
    "phone": "12147494207",
    "address": "",
    "notes": "Main 12147423000"
  },
  {
    "id": "seed-acct-51-64",
    "account_id": "acct-51",
    "full_name": "Brett Wallingford",
    "title": "",
    "email": "BWallingford@zelle.com",
    "phone": "12147494257",
    "address": "",
    "notes": "Main 12147423000"
  }
];
